const places = [
    {
        id: '1',
        name: 'Pad for Rent',
        location: 'Lapasan, CDOC',
        owner: 'Gemma Artes',
        contact: '09651548567',
        image: require('../assets/1.jpg'),
        details: "Pad for Rent for students and employees around Cagayan De Oro City. Please contact owner for more information",
        price: '2,000Php',
    },
    {
        id: '2',
        name: 'Room for Rent',
        location: 'Carmen, CDOC',
        owner: 'Bassey Daomar',
        contact: '09548561324',
        image: require('../assets/2.jpg'),
        details: "Room for Rent for students and employees around Cagayan De Oro City. Please contact owner for more information",
        price: '1,500Php',
    },
    {
        id: '3',
        name: 'Room for Rent',
        location: 'Agora, CDOC',
        owner: 'Ernest James Usaraga',
        contact: '09653584658',
        image: require('../assets/3.jpg'),
        details: "Room for Rent for students and employees around Cagayan De Oro City. Please contact owner for more information",
        price: '1,800Php',
    },
    {
        id: '4',
        name: 'Pad for Rent',
        location: 'Patag, CDOC',
        owner: 'Gerarld Agbon',
        contact: '09568648955',
        image: require('../assets/4.jpg'),
        details: "Pad for Rent for students and employees around Cagayan De Oro City. Please contact owner for more information",
        price: '2,200Php',
    },
    {
        id: '5',
        name: 'Pad for Rent',
        location: 'Gusa, CDOC',
        owner: 'Krishia Ocampo',
        contact: '09568455565',
        image: require('../assets/5.jpg'),
        details: "Pad for Rent for students and employees around Cagayan De Oro City. Please contact owner for more information",
        price: '1,850Php',
    },
];
export default places;